import { a, b, c, d, e, f } from './constants';
import { HexData } from './definitions';

export const topographyData: HexData = {
  volcano: [
    [0, 0],
    [0, f],
    [f, 0],
    [f, f],
  ],
  mountain: [
    [3, 2],
    [3, f],
    [8, f],
    [9, f],
    [a, 0],
    [c, 4],
    [d, b],
    [e, 0],
  ],
  hill: [
    [1, 2],
    [1, f],
    [3, 3],
    [6, f],
    [7, 4],
    [8, c],
    [9, 0],
    [9, 1],
    [9, e],
    [a, f],
    [d, 4],
    [e, 1],
    [f, 8],
  ],
  forest: [
    [2, f],
    [3, e],
    [4, 3],
    [4, 4],
    [5, 3],
    [5, e],
    [5, f],
    [7, 1],
    [8, 1],
    [8, 2],
    [a, 1],
    [c, d],
    [c, e],
    [d, c],
    [d, d],
    [d, e],
    [e, d],
    [e, f],
    [f, d],
    [f, e],
  ],
  plain: [
    [1, 1],
    [2, 2],
    [2, 3],
    [2, 8],
    [4, 5],
    [4, f],
    [5, 4],
    [5, 5],
    [6, 4],
    [6, 5],
    [6, e],
    [7, 2],
    [7, 8],
    [7, 9],
    [7, a],
    [7, b],
    [8, b],
    [9, 2],
    [c, c],
    [e, e],
  ],
  desert: [
    [7, 3],
    [7, 7],
    [8, 0],
  ],
  ocean: [[2, 9]],
};

export const enhancements: HexData = {
  cultivation: [
    [2, 8],
    [8, 2],
    [9, 1],
    [c, 4],
    [e, 1],
  ],
  'command-pavilion': [
    [2, 2],
    [4, 5],
    [7, b],
    [9, 0],
  ],
  factory: [
    [1, 2],
    [1, f],
    [2, 8],
    [2, f],
    [3, 3],
    [4, 4],
    [4, 5],
    [5, 5],
    [7, 1],
    [7, a],
    [8, 2],
    [8, 2],
    [9, 1],
    [9, f],
    [a, f],
    [d, d],
    [e, 1],
    [e, d],
    [e, e],
    [f, e],
  ],
  fortification: [
    [2, f],
    [a, f],
    [e, e],
    [e, f],
  ],
};

export const ownership: HexData = {
  'dewayne-bailiff': [
    [e, 0],
    [e, 1],
    [f, 0],
  ],
  'edward-grant': [
    [1, 1],
    [1, 2],
    [2, 2],
    [2, 3],
    [3, 2],
    [3, 3],
    [4, 3],
    [4, 4],
    [4, 5],
    [5, 3],
    [5, 4],
    [5, 5],
    [6, 4],
    [6, 5],
    [7, 3],
    [7, 4],
  ],
  'jayson-rittersdorf': [
    [7, 1],
    [7, 2],
    [8, 0],
    [8, 1],
    [8, 2],
    [9, 0],
    [9, 1],
    [9, 2],
    [a, 0],
    [a, 1],
  ],
  'joel-david': [
    [8, f],
    [9, e],
    [9, f],
    [a, f],
  ],
  'jaleh-noah': [
    [1, f],
    [2, f],
    [3, e],
    [3, f],
    [4, f],
    [5, e],
    [5, f],
    [6, e],
    [6, f],
  ],
  'rob-mountney': [
    [e, d],
    [e, e],
    [e, f],
    [f, d],
    [f, e],
    [f, f],
  ],
  'jon-arford': [
    [7, 7],
    [7, 8],
    [7, 9],
    [7, a],
    [7, b],
    [8, b],
    [8, c],
  ],
  'nathaniel-palmer': [[f, 8]],
  'shad-feenstra': [
    [c, d],
    [c, e],
  ],
  'victor-romine': [
    [c, c],
    [d, b],
    [d, c],
    [d, d],
    [d, e],
  ],
  'tom-galbreath': [
    [c, 4],
    [d, 4],
  ],
  'jared-macnaughton': [
    [2, 8],
    [2, 9],
  ],
};
export const orderOfBattles: HexData = {
  'dewayne-bailiff': [
    [e, 0, 'Sixth Plague Company -- Garrison'],
    [e, 1, 'Sixth Plague Company p2 -- Move(1/2)'],
  ],
  'edward-grant': [
    [7, 4, 'Tzican Infiltrators -- Move (1/2)'],
    [7, 3, 'The Changing March -- Move (1/2)'],
    [5, 5, 'Never Ending Change -- Garrison'],
    [4, 5, 'The Variance Reversal -- Garrison'],
    [7, 3, 'Next Swirl -- Move (1/2)'],
    [7, 4, 'Raptors Call -- Garrison'],
  ],
  'joel-david': [
    [9, e, 'Company One -- Garrison'],
    [8, f, 'Company Two -- Garrison'],
    [9, e, 'Company Three -- Garrison'],
  ],
  'jaleh-noah': [
    [6, e, 'War band One -- Garrison'],
    [6, f, 'War Band Three -- Move (1/2)'],
    [6, f, 'War band Two -- Move (1/2)'],
  ],
  'jayson-rittersdorf': [
    [a, 0, 'Porphyria -- Garrison'],
    [8, 1, 'Alkaptonuria -- Build Pavilion (1/3)'],
    [9, 2, 'Yunis Varon -- Build Pavilion (1/3)'],
    [7, 1, 'Wandering Spleen -- Garrison'],
    [7, 2, 'Dracunculosis -- Garrison'],
  ],
  'rob-mountney': [
    [e, e, 'Two -- Garrison'],
    [f, e, 'One -- Garrison'],
    [e, d, 'Three -- Garrison'],
  ],
  'jon-arford': [
    [8, c, 'Troupe One -- Garrison'],
    [7, b, 'Troupe Two -- Garrison'],
  ],
  'nathaniel-palmer': [[f, 8, 'Carde One - Garrison']],
  'shad-feenstra': [[c, d, '-- Garrison']],
  'victor-romine': [
    [d, d, 'One -- Build Pavilion (2/3)'],
    [d, b, 'Two -- Garrison'],
  ],
  'tom-galbreath': [[d, 4, 'Sovereigns First -- Garrison']],
  'jared-macnaughton': [
    [2, 8, "Timm Timm's Friends -- Garrison"],
    [2, 9, 'Two -- Build Pavilion (1/3)'],
  ],
};
